### ISSUE TITLE
Remove locations of observations flagged as thinned out after HofX

### ISSUE THREAD

**Issue by ibanos90** [NCAR/MPAS-Workflow#170]
In order to remove the locations of observations flagged as thinned out after the Gaussian QC filter by the HofX application,  the following steps are needed:

- [x] Add an HofX task to create IODAv2 files with flagged data after thinning. This task needs to be able to run along an HofX application executed for verification
- [x] Create a task in the workflow to remove the thinned observations by calling a python script that actually does it (this can be done offline, but I already added it to the workflow for the future use in the real-time run)
- [ ] Create a python script that gets the data from HofX and puts all files together in one IODAv2 file removing the locations flagged as thinned observations  (almost, but not completed)
- [ ] Run experiment using Jake's configuration (30-60km amsua_mhs_clrsky_varbc experiment)

Working feature branches: 
- https://github.com/NCAR/MPAS-Workflow/tree/feature/removeThinnedObs
- https://github.com/NCAR/MPAS-Workflow/tree/feature/expIASI_30-60J

**Comment by jjguerrette** [comment]
Thank you @ibanos90 for setting out those tasks.  Actually the third bullet can be avoided by telling the HofX application to write out only 1 `obsout` file per observation space.  That is easily controlled in the YAML in the first step.

A note to @liujake:  I asked @ibanos90 to create this issue so that we have documentation of the completed steps and the work that remains.  We will need to figure out who will do this work going forward now that @ibanos90 is moving to her new position.
