### ISSUE TITLE
Check how OOPS IncrementEnsemble optimization affects 80-member performance

### ISSUE THREAD

**Issue by jjguerrette** [NCAR/MPAS-Workflow#172]
See https://github.com/JCSDA-internal/oops/pull/1990.

80-member experiments (e.g., 60km EDA and 30-60km EnVar) might run on fewer nodes or at least low-memory nodes due to memory reduction.

**Comment by andreapiacentini** [comment]
I really hope so.  
In the AQ application we have relatively few observations compared to the size of the state, therefore we opted for a dual minimizer (RPLanczos) in order to avoid the storage of orthogonalization pairs in the model space and it's also hugely reduces the memory requirements. We have noticed that the implementation of the dual minimizers is lacking some diagnostics w.r.t. the primal counterpart. If you also opt for them, we could open an issue on the subject. Selimé Gurol from CERFACS is ok for helping on it, if needed.

**Comment by jjguerrette** [comment]
My hope is that the memory will be reduced in the 80-member EnVar cases we run, because the ensemble accounts for a large portion of the memory.  Halving the Increment/State footprint might be noticeable.

Still, observations do make up a significant portion of memory for our use cases.  Our most basic case assimilates 788K observations.  Additional memory is used for all the thinned radiance and satellite AMV locations as well.  Then we are testing with more expensive cases that add hyperspectral and geostationary IR radiances.  So I'm not sure the dual minimizer will be useful for us in the long term as we add many more observations.  Is the dual minimizer always more efficient (for memory and/or computations) when the state vector is larger than the obs vector?  Or is there some other limit?

**Comment by andreapiacentini** [comment]
Hi Jonathan, Selimé confirms that  

> To answer Jonathan, yes dual minimizers are interesting when the number of observations are less than the dimension of the state dimension, If the number of observations getting closer to the dimension of the state, of course there is no interest to use dual minimizer then. I do no think that there is any other limitation. Only limitation second level preconditioning is less efficient.  

Related to the second level preconditioning, I know that it is in general harder to implement a proper minimization restart with an outer loop. We don't plan (neither we could afford) an outer loop in our 4DEnsVar.  
I hope it helps. Anyway it is worth a try: luckily in OOPS is just a question of changing one line in the yaml configuration.  

By the way, Anna already merged the IncrementEnsemble optimization in oops develop.

**Comment by jjguerrette** [comment]
Thank you for the additional info.  We need to use more than one outer loop iteration.

**Comment by andreapiacentini** [comment]
Ok, is debatable then, even if technically feasible: NEMOVAR is implementing an outer loop with the dual RPCG minimizer. Impact on memory there is justifying some more coding.  
Anyway, I am curious to know if the IncrementEnsemble new storage is making a difference or if the minimizer is casting shadow on this improvement.  
Cheers. A.

**Comment by liujake** [comment]
I made two standard hybrid-3DEnVar runs: one with 25 Oct. code and another with Today's code (as of 5 Dec.). Both runs have 2 outer loops with 60 inner loops per outer loop. Used 6 large memory nodes (109GB per node) with 32 cores/node.
Timing and memory use are very similar between two versions of mpas-jedi code.

Timing and memory use with code of 25 Oct. 2022:
```
- Runtime:    689.33 sec,  Memory: total:   275.46 Gb, per task: min =     1.34 Gb, max =     2.77 Gb
```

Timing and memory use with code of 5 Dec. 2022:
```
- Runtime:    697.05 sec,  Memory: total:   271.19 Gb, per task: min =     1.31 Gb, max =     2.76 Gb
```

**Comment by liujake** [comment]
These hybrid-3DEnVar runs use 80-member ensemble input at 60-km grid spacing. As memory use from observations will be independent of model resolution, the benefit from https://github.com/JCSDA-internal/oops/pull/1990 should be larger with a higher model resolution.

**Comment by andreapiacentini** [comment]
It depends on the minimizer you are using. If it involves storing pairs of control vectors in the orthogonalization base, the memory usage increases linearly and it is proportional to the model resolution. That's why I mentioned dual minimizers, which have a memory usage which depends on the size of the observations vector, but which require a bit of care when the outer loop is on.  
Since oops is only providing a high watermark of memory usage, I run a very simple homemade tool (meaningful only if your computational nodes are dedicated) for generating a timeline of memory usage. Sometime it gives some hints on why and when the application is so greedy. I'd be happy to share it if you think it's useful.

**Comment by liujake** [comment]
@andreapiacentini  We are using DRIPCG minimizer.

**Comment by liujake** [comment]
Do I need to modify yaml to make the new constructor work? I did NOT change yaml when making the tests.

**Comment by andreapiacentini** [comment]
If you look at lines 117 and following of `oops/src/oops/assimilation/DRIPCGMinimizer.h` you'll see
  ```
  std::vector<CtrlInc_> vvecs;  // for re-orthogonalization
  std::vector<CtrlInc_> zvecs;  // for re-orthogonalization
  std::vector<double> scals;  // for re-orthogonalization
  // reserve space in vectors to avoid extra copies
  vvecs.reserve(maxiter+1);
  zvecs.reserve(maxiter+1);
```
reserving `maxiter+1` pairs or `CtrlInc_` objects, in your case 122 objects on the model grid times the number of variables in the control space.

In principle you only had to make sure that oops has been recompiled, but the yaml stay the same. It is meant to work both for the full list of `members` or the compact `members from template` entry.

**Comment by liujake** [comment]
Yes. The new version of code was recompiled from the scratch. Even though our ensemble and increment are at a low resolution (60 km), I expected more reduction on the memory use as the ensemble memory use is reduced to the half with the new constructor. Does this 'half' ensemble effect only for dual minimizer, not for primal minimizer like DRIPCG?

**Comment by andreapiacentini** [comment]
It very much depends on a combination of factors, including the compiler.  
The difference in the high watermark of a dirac4d test (if you implemented one) should be evident, since in such a case you just load an ensemble and apply a possibly localized B matrix product. If you have such a test, I'd be happy to know if you see any difference.   
But in the case of a 4DEnsVar, the old implementation was loading the full states ensemble and building the full increments (w.r.t. mean) ensemble. They were residing together in memory for a moment. Then in principle the states ensemble is freed, but our Intel OneAPI compiler is not very smart in recovering memory. If your compiler knows how to recover the freed memory, the high watermark is hit when both ensembles are in memory, then the current memory usage lowers, but later on the minimizer is adding up to the max of the application. With a dual minimizer and relatively less observations than d.o.f. in the control increment, the minimizer is never building up as much storage as a full states ensemble.  
That's why I suggested to draw a timeline of memory usage so that you can easily distinguish the ensemble loading phase from the minimization iterations.

**Comment by liujake** [comment]
Thanks for detailed explanation. Now I understand better. We use gnu compiler, which might free ensemble memory in the later stage of hybrid-3DEnVar. We do have some dirac (perhaps 3D) test. We will let you know the difference for dirac test. Not sure whether we can output a timeline of memory usage with current code. I do feel the large memory use is one of current computational bottlenecks and hope more optimizations like this could be figured out.

**Comment by andreapiacentini** [comment]
I can show you, if we arrange a way to do so, a very simple (but really very simple) shell script that can run in background and sample memory usage every N seconds (I use to run it with a 1 second sample for picking the main steps, otherwise it can smooth out the curves.  
Running a background script in a scheduled job can be tricky. I know how to do it with slurm. If you use slurm, the tool will work off the shelf, otherwise you have to "translate" from slurm to your job manager (they are usually all able to perform the same tasks, it's a mere question of syntax).

**Comment by liujake** [comment]
@andreapiacentini That will be cool! I sent you an email to meet.

**Comment by jjguerrette** [comment]
Thank you for checking @liujake.  Since there was not much impact, I'm closing this.  Reopen or create new issue if you feel the discussion needs to continue on GitHub.
