### ISSUE TITLE
Add Acknowledgements and Contributors sections in the Readme

### ISSUE THREAD

**Issue by ibanos90** [NCAR/MPAS-Workflow#80]
Add a **Contributors** section in the Readme where all contributors from our group can be listed as co-authors. Also, an **Acknowledgement** section:
- Jamie Bresch (@jamiebresch) for the obs2ioda converter (https://github.com/jamiebresch/obs2ioda) developments. In addition, the script GetRDAobs.csh in this workflow is based on rda_obs2ioda.csh from that repository;
- CISL for computing resources and assistance: https://arc.ucar.edu/knowledge_base/75694398

**Comment by jjguerrette** [comment]
Another acknowledgement for Craig Schwartz for the MPAS `meanStateExe` source code and build.

- Craig Schwartz (@weather4evr) for providing the MPAS mean-state calculation program, which is used in verification and forecasting for ensemble cycling applications

**Comment by jjguerrette** [comment]
Overall, we need to discuss internally in PARC as well. Let's do that before adding too many more items in this issue (my mistake).  Co-contributors that submit PR's are given credit via GitHub PR's as well.  My main motivation for these sections is to give credit to those who have contributed significantly, but would otherwise go unnoticed.
